version: "3"

vars:
  IMG: bootchain-operator:latest
  CRD_NAME: core.bootchain.ruicoelho.dev_bootdependencies.yaml

tasks:
  # ── CRD ────────────────────────────────────────────────────────────────────
  install-crd:
    desc: Install the BootDependency CRD into the current cluster
    cmds:
      - kubectl apply -f config/crd/bases/{{.CRD_NAME}}

  uninstall-crd:
    desc: Remove the BootDependency CRD from the current cluster
    cmds:
      - kubectl delete -f config/crd/bases/{{.CRD_NAME}} --ignore-not-found

  # ── Run locally ────────────────────────────────────────────────────────────
  run:
    desc: Run the operator locally (controller only, webhooks disabled)
    deps: [install-crd]
    cmds:
      - ENABLE_WEBHOOKS=false go run ./cmd/main.go

  run-with-webhook:
    desc: Run the operator locally with webhooks enabled (requires dev certs)
    deps: [install-crd]
    vars:
      CERT_DIR: /tmp/bootchain-webhook-certs
    cmds:
      - go run ./cmd/main.go
          --webhook-cert-path={{.CERT_DIR}}
          --webhook-cert-name=tls.crt
          --webhook-cert-key=tls.key

  webhook-proxy:
    desc: Start socat proxy so the Colima VM (IPv4) can reach the webhook server (IPv6 socket on macOS)
    cmds:
      - socat TCP4-LISTEN:9444,fork,reuseaddr TCP6:[::1]:9443

  # ── Webhook dev setup ───────────────────────────────────────────────────────
  webhook-gen-certs:
    desc: Generate self-signed TLS certs for local webhook development
    cmds:
      - bash hack/gen-dev-certs.sh

  webhook-register:
    desc: Register webhook configurations pointing to localhost
    cmds:
      - bash hack/register-dev-webhook.sh

  webhook-enable-namespace:
    desc: Label the default namespace to activate the dev webhook
    cmds:
      - kubectl label namespace default bootchain-webhook=enabled --overwrite

  webhook-disable-namespace:
    desc: Remove the webhook label from the default namespace
    cmds:
      - kubectl label namespace default bootchain-webhook- --overwrite || true

  webhook-teardown:
    desc: Remove the dev webhook configurations from the cluster
    cmds:
      - kubectl delete mutatingwebhookconfiguration bootchain-dev-webhook --ignore-not-found
      - kubectl delete validatingwebhookconfiguration bootchain-dev-validating-webhook --ignore-not-found

  webhook-setup:
    desc: Full dev webhook setup (certs + register + label namespace)
    cmds:
      - task: webhook-gen-certs
      - task: webhook-register
      - task: webhook-enable-namespace

  # ── Samples ────────────────────────────────────────────────────────────────
  apply-sample:
    desc: Apply the sample BootDependency manifest
    cmds:
      - kubectl apply -f config/samples/core_v1alpha1_bootdependency.yaml

  delete-sample:
    desc: Delete the sample BootDependency manifest
    cmds:
      - kubectl delete -f config/samples/core_v1alpha1_bootdependency.yaml --ignore-not-found

  # ── Helm ───────────────────────────────────────────────────────────────────
  helm-lint:
    desc: Lint the Helm chart
    cmds:
      - helm lint charts/bootchain-operator

  helm-template:
    desc: Render the Helm chart templates to stdout
    vars:
      RELEASE: "{{.RELEASE | default \"bootchain-operator\"}}"
      NAMESPACE: "{{.NAMESPACE | default \"bootchain-operator-system\"}}"
    cmds:
      - helm template {{.RELEASE}} charts/bootchain-operator --namespace {{.NAMESPACE}}

  helm-install:
    desc: Install the Helm chart into the cluster
    vars:
      RELEASE: "{{.RELEASE | default \"bootchain-operator\"}}"
      NAMESPACE: "{{.NAMESPACE | default \"bootchain-operator-system\"}}"
    cmds:
      - kubectl create namespace {{.NAMESPACE}} --dry-run=client -o yaml | kubectl apply -f -
      - helm upgrade --install {{.RELEASE}} charts/bootchain-operator
          --namespace {{.NAMESPACE}}
          --set image.repository={{.IMG | replace ":latest" ""}}
          --set image.tag=latest
          --wait

  helm-uninstall:
    desc: Uninstall the Helm release from the cluster
    vars:
      RELEASE: "{{.RELEASE | default \"bootchain-operator\"}}"
      NAMESPACE: "{{.NAMESPACE | default \"bootchain-operator-system\"}}"
    cmds:
      - helm uninstall {{.RELEASE}} --namespace {{.NAMESPACE}} --ignore-not-found

  # ── Docs ───────────────────────────────────────────────────────────────────
  docs-serve:
    desc: Serve the MkDocs documentation locally (with live reload)
    cmds:
      - source venv/bin/activate && mkdocs serve

  docs-build:
    desc: Build the MkDocs documentation into the site/ directory
    cmds:
      - source venv/bin/activate && mkdocs build --strict

  docs-deploy:
    desc: Deploy the MkDocs documentation to GitHub Pages
    cmds:
      - source venv/bin/activate && mkdocs gh-deploy --force
